### ISSUE TITLE
built-in `tar:` provider

### ISSUE THREAD

**Issue by pi0** [unjs/giget#10]
Support a built-in provider to automatically resolve from a URL to a tar file

**Comment by eulier1** [comment]
What would be the use case for this?. Just wanna understand it with an example to see if I can help.

**Comment by pi0** [comment]
This way we can support any artillery template provider using a known convention without the need to create a custom one, out of the box.

Something like this: `tar:https://my-template-registry.com/template/v1.tar#name=pikachu&version=1.0.0`

Resolves to:

```json
    name: 'pikachu',
    version: '1.0.0',
    tar: `https://my-template-registry.com/template/v1.tar`
```

This way, other than custom CDN, we can support npm registry and github releases as template provider! Examples:

- https://registry.npmjs.org/unstorage/-/unstorage-0.0.0.tgz
- https://github.com/unjs/unstorage/archive/refs/tags/v0.6.0.tar.gz

**Comment by alexanderkorytskyi** [comment]
@pi0 I can take this if you approve the scope described above

**Comment by JupaCCLH** [comment]
When will this functionality be in master?
