### ISSUE TITLE
CLI can not be used

### ISSUE THREAD

**Issue by byronogis** [unjs/giget#135]
### Environment

❯ node -v         
v20.10.0

❯ npm -v          
10.2.3

### Reproduction

❯ npx giget@1.2.0 gh:unjs/template

/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 1: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 2: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 3: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 4: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 5: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 6: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 7: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 8: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 9: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 10: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 11: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 12: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 13: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 14: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 15: import: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 17: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 18: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 19: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 20: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 21: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 22: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 23: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 24: const: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 25: .:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 26: import:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 27: types:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 28: default:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 29: },: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 30: require:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 31: types:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 32: default:: command not found
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 33: syntax error near unexpected token `}'
/Users/byron/.npm/_npx/a37ce48c408dc016/node_modules/.bin/giget: line 33: `		}'

### Describe the bug

Look like the cli file not run in node environment.

I think the reason for that is in [here](https://github.com/unjs/giget/commit/10f62bf45e0ed60e15d1372dd6908568b824233e#diff-fa8d4e24d8399e8350f1c8bad05df53e8032ea995835bf911507015e2db61cddL1).

**Comment by pi0** [comment]
Thanks for notice ❤️ Should be fixed in last release.
