### ISSUE TITLE
Cannot resolve "node-fetch-native/native/proxy" from "..." and externals are not allowed!

### ISSUE THREAD

**Issue by vejja** [unjs/giget#140]
### Environment

giget 1.2.1
Node 18
Nuxt 3.8.2, 3.9.0, 3.9.1
Nitro 2.8.1

### Reproduction

Sorry unable to provide repro as this only appears in workers environment
This was reported on Cloudflare, Vercel

Does not appear in NodeJS, local environments

### Describe the bug

Initial bug report was filed in Nuxt-Security [there](https://github.com/Baroshem/nuxt-security/issues/335)
We initially thought the issue was on our side but were unable to reproduce

Then one user filed logs, and we realized the error was triggered by `giget` while trying to use `node-fetch-native` in Workers environments

### Additional context

- The error did not exist before Nuxt 3.8.2
- Nuxt 3.8.2 upgraded `nitropack` to 2.8.1
- `nitropack@2.8.1` upgraded `node-fetch-native` to 1.6.1
- The log report shows that `giget` is trying to use `node-fetch-native`'s proxy feature, which was not available in 1.4.1
- Nuxt-Security uses `node-fetch-native` 1.4.1

This looks like a version dependency mismatch on `node-fetch-native`
This is very strange because package managers should usually be able to resolve the correct version without any issue
In fact, in NodeJS environments the issue does not exist

However for some unknown reason, it seems to affect Workers environment

### Logs

```sh
(node-resolve plugin) Could not resolve import "node-fetch-native/native/proxy" in /opt/_work/myproject/node_modules/.pnpm/giget@1.2.1/node_modules/giget/dist/index.mjs using exports defined in /opt/_work/myproject/node_modules/.pnpm/node-fetch-native@1.6.1/node_modules/node-fetch-native/package.json.
Error:  [nitro] Error: Cannot resolve "node-fetch-native/native/proxy" from "/opt/_work/myproject/node_modules/.pnpm/giget@1.2.1/node_modules/giget/dist/index.mjs" and externals are not allowed!


undefined
Error:  Cannot resolve "node-fetch-native/native/proxy" from "/opt/_work/myproject/node_modules/.pnpm/giget@1.2.1/node_modules/giget/dist/index.mjs" and externals are not allowed!
  at Object.resolveId (node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:1973:17)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:18542:28)
  at async resolveId (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17211:26)
  at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17625:15)
  at async Object.resolveId (node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:588:10)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:18542:28)
  at async resolveId (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17211:26)
  at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17625:15)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:18542:28)
  at async resolveId (node_modules/.pnpm/rollup@4.9.2/node_modules/rollup/dist/es/shared/node-entry.js:17211:26) 

Error:  Cannot resolve "node-fetch-native/native/proxy" from "/opt/_work/myproject/node_modules/.pnpm/giget@1.2.1/node_modules/giget/dist/index.mjs" and externals are not allowed!
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by pi0** [comment]
Hi. Please try recreating your lockfile using `npx nuxi upgrade --force` this ensures to use latest compatible node-fetch-native build. unofrotounatly nothing we can do in giget itself to mitigate package manager hoisting issues.

**Comment by tkjaergaard** [comment]
I'm experiencing this bug as well in a non-nuxt Bun project.

```
$ bun build src/index.ts --outdir dist --target node
11 | import { fetch } from 'node-fetch-native/proxy';
              ^
error: No matching export in "node_modules/node-fetch-native/dist/proxy.cjs" for import "fetch"
    at /Users/thomaskjaergaard/projects/internal/wah-cli-v3/node_modules/giget/dist/index.mjs:11:10
error: script "build" exited with code 1
```

**Comment by pi0** [comment]
@tkjaergaard can you please share your project or a reproduction? 🙏🏼

**Comment by tkjaergaard** [comment]
@pi0 

Bun: 1.0.25

Git repo: https://github.com/tkjaergaard/giget-bun-reproduction

**Steps to reproduce**
1. Clone repository
2. Install Bun version 1.0.25 (https://bun.sh)
3. Run build command
```bash
$ bun build index.ts --outdir=dist --target=node
```


**Error**
```
11 | import { fetch } from 'node-fetch-native/proxy';
              ^
error: No matching export in "node_modules/node-fetch-native/dist/proxy.cjs" for import "fetch"
    at /Users/thomaskjaergaard/projects/internal/giget-bun-reproduction/node_modules/giget/dist/index.mjs:11:10
```

**Comment by pi0** [comment]
Thanks. I will investigate in https://github.com/unjs/giget/issues/145 👍🏼
