### ISSUE TITLE
[bun] No matching export in "node_modules/node-fetch-native/dist/proxy.cjs"

### ISSUE THREAD

**Issue by pi0** [unjs/giget#145]
Bun: 1.0.25

Git repo: https://github.com/tkjaergaard/giget-bun-reproduction

**Steps to reproduce**
1. Clone repository
2. Install Bun version 1.0.25 (https://bun.sh)
3. Run `bun install` to install dependencies
4. Run build command
```bash
$ bun build index.ts --outdir=dist --target=node
```

**Error**
```
11 | import { fetch } from 'node-fetch-native/proxy';
              ^
error: No matching export in "node_modules/node-fetch-native/dist/proxy.cjs" for import "fetch"
    at /Users/thomaskjaergaard/projects/internal/giget-bun-reproduction/node_modules/giget/dist/index.mjs:11:10
```

_Originally posted by @tkjaergaard in https://github.com/unjs/giget/issues/140#issuecomment-1910092203_

**Comment by tkjaergaard** [comment]
If i set the build target to `browser` it works. But if i set it to `bun` or `node` i get the error.

When running the script using `bun index.ts`, i don't see the error either 🤔

**Comment by tkjaergaard** [comment]
@pi0 any progress on this? 😊

**Comment by pi0** [comment]
Hi. It is definitely on my track. only 24h per day is not enough ([notes](https://github.com/pi0/tired-maintainer)) 😅

**Comment by tkjaergaard** [comment]
@pi0 All good, just interested in where this was stranded 💪

**Comment by tkjaergaard** [comment]
@pi0 I've identified the issue. It's related to [unjs/node-fetch-native](https://github.com/unjs/node-fetch-native/tree/main).

I've re-created the issue here: [https://github.com/unjs/node-fetch-native/issues/114](https://github.com/unjs/node-fetch-native/issues/114).

**Comment by tkjaergaard** [comment]
@pi0 Think this should be closed since we fixed it in https://github.com/unjs/node-fetch-native/issues/114 😊✌️

**Comment by tuler** [comment]
This is still happening to me
`giget@2.0.0`
bun 1.3.5
