### ISSUE TITLE
Disable `--install` until `nypm` has better ways of detecting the package manager

### ISSUE THREAD

**Issue by JakeIsMeh** [unjs/giget#149]
### Environment

giget@1.2.1
Node 20.7.0
npm 10.1.0
pnpm 8.15.1

### Reproduction

```npx giget@latest nitro nitro-app --install```
or
```pnpx giget@latest nitro nitro-app --install```

### Describe the bug

Because nypm's package manager detection depends on either the lockfile being present or the package manager being specified in package.json, following the quick start guide for Nitro, which uses `--install`, causes it to complain that no package managers were detected.

### Logs

```sh
> pnpm dlx giget@latest nitro --install
Packages: +34
++++++++++++++++++++++++++++++++++
Progress: resolved 34, reused 34, downloaded 0, added 34, done

 ERROR  No package manager auto-detected.
```

**Comment by pi0** [comment]
Let's track where the issue is https://github.com/unjs/nypm/issues/89

**Comment by pi0** [comment]
Released https://github.com/unjs/nypm/releases/tag/v0.3.7 testing if it can help in these situations.

**Comment by JakeIsMeh** [comment]
Just tested it, works with `npx` and `pnpm dlx`
