### ISSUE TITLE
Option to throw if fetching a template fails

### ISSUE THREAD

**Issue by MuhammadM1998** [unjs/giget#154]
### Describe the feature

Hello 👋

I'm using a Nuxt layer with the GitHub repo approach which lacks the versioning we would get if it were a npm package.
Hence I want to make sure that I'm using the latest layer commit and otherwise fail to catch bugs as early as possible.
Currently, If I set any incorrect `GIGET_AUTH` env (Repo is private) it doesn't throw an error and uses the currently folder in `node_modules`.
A flag that throws an error and/or warning if fetching the repo fails would be great! Thanks a lot!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ndragun92** [comment]
I think it doesnt throw error coz it created .cache folder already.
If you delete .cache folder and then refetch with wrong token you will get error

This is example on how it can be handled


```
import { downloadTemplate } from 'giget'
import dotenv from 'dotenv'

// Load environment variables from .env file
dotenv.config()

const token = process.env.GITHUB_TOKEN

if (!token) {
  console.error('MISSING GITHUB_TOKEN TO FETCH TYPES')
  process.exit(1)
}

try {
  await downloadTemplate('github:username/:repository/:folder#branch', {
    dir: '.types',
    offline: false,
    preferOffline: false,
    force: true,
    forceClean: true,
    provider: 'github',
    auth: token
  }
  )
  console.info('Successfully fetched types')
} catch (e) {
  if (e && e.message && typeof e.message === 'string') {
    console.error('Error fetching types', e.message)
  } else {
    console.error('Error fetching types', e)
  }
  process.exit(1)
}
```

Hope it helps @MuhammadM1998
