### ISSUE TITLE
Bump the version to fix a vulnerability

### ISSUE THREAD

**Issue by alex-golubtsov** [unjs/giget#184]
### Describe the feature

Version `1.2.3` contains `tar@6.2.0`, which has a [vulnarability](https://security.snyk.io/package/npm/tar/6.2.0). Master branch already has `tar@6.2.1`,  please bump the version

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
`"tar": "^6.2.1"` in package json, is a caret range (not pinned). meaning, package managers install latest 6.x. You have to fresh your package manager lockfile.

Besides, the clonned template sources should be trusted.
