### ISSUE TITLE
CLI: Change the directory to the new successfully cloned repo

### ISSUE THREAD

**Issue by edimitchel** [unjs/giget#2]
To avoid cd into the new repo after the cloning, add on the CLI an opt-in feature to do the directory change automatically

Bonus: an opt-out feature to automatically install deps using `ni` ?

**Comment by pi0** [comment]
Both nice ideas! We can use `process.chdir()` so rest of Node.js operations are relative to new dir. But it won't update the CWD in shell that is running process. How do you imagine it?


For auto install, I'm working on another unjs package similar to ni. We could integrate it surely 👍🏼

**Comment by edimitchel** [comment]
> Both nice ideas! We can use `process.chdir()` so rest of Node.js operations are relative to new dir. But it won't update the CWD in shell that is running process. How do you imagine it?
An **unjs** project to update cwd using a intelligent `spawn('bash')` ?

> For auto install, I'm working on another unjs package similar to ni. We could integrate it surely 👍🏼
👍🏻

**Comment by pi0** [comment]
Added an experimental `--shell` flag. Only stable implementation could find was using `spawnSync` and keeping current Node.js process alive (async stdin was unstable in MacOS at least to detach). If you have better ideas PR more than welcome 👍🏼
