### ISSUE TITLE
Replace `tar` w/ `tar-stream`

### ISSUE THREAD

**Issue by SukkaW** [unjs/giget#201]
### Describe the feature

`tar` uses `minipass` (and `fs-minipass` and `minizlib`) as their stream implementation. However we don't utilize any features provided by `minipass`, we only need a normal Node.js stream. We can replace `minipass` w/ `tar-stream` (with manual `fs.createWriteStream`) which is more lightweight.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Plan is migrate to nanotar (https://github.com/unjs/giget/issues/131)
