### ISSUE TITLE
Readme section on differences between degit/tiged

### ISSUE THREAD

**Issue by grikomsn** [unjs/giget#3]
Hey! After seeing this being published, definitely gonna be my default cloner after using degit/tiged. Curious what are the differences between other packages? I'd love to help contribute the readme.

**Comment by pi0** [comment]
digit and tiged _also_ support tarball download but also depend on local git for operations like getting HEAD ref and i found it so unstable and finally made a minimal rewrite to purely use fetch. Also it fixes some issues with subpath cloning.

**Comment by pi0** [comment]
Okay now giget is expanded to a generic template cloning utility. Would you still like to contribute on docs to add more info about differences from alternatives?

**Comment by grikomsn** [comment]
Yes for sure! Gonna read the new docs and try my best to add a section.
