### ISSUE TITLE
issue with private bitbucket repo

### ISSUE THREAD

**Issue by Riadz** [unjs/giget#74]
### Environment

OS: Windows 10
Node: v16.17.0

### Reproduction

i created a new private empty bitbucket repo for this issue, so i don't mind sharing the key :).

`npx giget bitbucket:riad_hachemane/test-giget-bitbucket --auth kuhyURjJB7gMoqURJMIP`

### Describe the bug

@pi0 
am having trouble with a private bitbucket repo, the auth token is not working,
i created a new private empty bitbucket repo for this issue, so i don't mind sharing the key :).
steps i made to get to this issue:

### 1) make public bitbucket repo, and used giget, works as expected ✅
![2023-01-16 09_36_43-Window](https://user-images.githubusercontent.com/46753769/212635901-0cce3082-3864-45d3-a8f8-e85e4264f38a.png)

### 2) made that repo private, also as expected ✅
![2023-01-16 09_41_04-Window](https://user-images.githubusercontent.com/46753769/212635982-59816266-86ae-46f7-919d-0eca66ff3d89.png)

### 3) add a "Repository Access Token" from bitbucket dashboard, and give it all permissions ✅
![2023-01-16 09_55_22-Window](https://user-images.githubusercontent.com/46753769/212637555-117d3856-5c8e-4b56-b16c-ba327a26523d.png)

### 4) use it with `--auth`, doesn't work ❌
![2023-01-16 09_55_55-Window](https://user-images.githubusercontent.com/46753769/212637386-c8218a12-9b67-46f9-a1b7-85979ef0679a.png)

**Comment by Riadz** [comment]
update: bitbucket actually returns a response when using CURL

![2023-01-16 10_36_55-Window](https://user-images.githubusercontent.com/46753769/212645896-328c2272-d8ae-494e-bf08-83298d60dcf8.png)

hope this is helpful.

**Comment by Dominic-Marcelino** [comment]
@Riadz I think that's related to #46 

The bitbucket endpoint also doesn't seem to accept the scoped token. Try to use an account-token

**Comment by pi0** [comment]
let's track via #104
