### ISSUE TITLE
`downloadTemplate` broken since last update

### ISSUE THREAD

**Issue by Princesseuh** [unjs/giget#81]
### Environment

Node v16.19.0, pnpm, macOS

### Reproduction

Your own CI

### Describe the bug

Since the latest update (1.1.0), `downloadTemplate` returns a 400 on Node 16 while hitting GitHub. This happens in `giget` CI, but is also breaking people downstream, including `create-astro`.

![image](https://user-images.githubusercontent.com/3019731/219662178-494f8b7a-ae97-45b2-bf97-ee5fb7fd9c63.png)

The original PR (https://github.com/unjs/giget/pull/77) also had this test fail.

### Logs

```sh
Failed to download https://github.com/unjs/template/archive/main.tar.gz: 400 Bad Request
```

**Comment by pi0** [comment]
Should be fixed in latest release.

**Comment by Princesseuh** [comment]
Thank you for the quick fix!
